### ISSUE TITLE
Overhyped, OK Development Though

### ISSUE THREAD

**Issue by uupf** [notspeezy/x444-Nuker#3]
Very overhyped (by you, at the most) I was expecting more. This could easily be developed in 5 minutes by a skid.. Good work though 🤷

**Comment by notspeezy** [comment]
Not my fault if you've been hyped at this point. A nuker stays a nuker. 50 requests/s is the max we can do.

**Comment by notspeezy** [comment]
Would you mind to tell me your cord though

**Comment by uupf** [comment]
My discord is blit#0001

**Comment by ghost** [comment]
max 50 rq/s is kinda low tbh, a lot of the code can be improved by using python 3.10's new `match` statement

**Comment by ghost** [comment]
also, you should use `fstrings` over string.format(), because of readability and performance

**Comment by notspeezy** [comment]
> max 50 rq/s is kinda low tbh, a lot of the code can be improved by using python 3.10's new `match` statement

50 req/s is the max that discord allows us

**Comment by notspeezy** [comment]
> also, you should use `fstrings` over string.format(), because of readability and performance

I've heard than using string formats is faster than fstrings. But can still change that

**Comment by Its-Vichy** [comment]
> > max 50 rq/s is kinda low tbh, a lot of the code can be improved by using python 3.10's new `match` statement
> 
> 50 req/s is the max that discord allows us

This is where ingenuity must be present to overcome this limit, and what makes your tool poorly coded and inefficient.
